apiVersion: apps/v1
kind: Deployment
metadata:
  name: kb-apiprod
spec:
  selector:
    matchLabels:
      app: kb-apiprod
  template:
    metadata:
      labels:
        app: kb-apiprod
    spec:
      containers:
      - name: kb-apiprod
        image: brunomor7/k8s-api-produto:1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: kb-apiprod
spec:
  selector:
    app: kb-apiprod
  ports:
  - port: 80
    targetPort: 8080
